# Generated by Django 6.1.2 on 2026-10-09 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(db_index=True)),
                ('problem_id', models.UUIDField(db_index=True)),
                ('language_id', models.CharField(max_length=64)),
                ('source', models.TextField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('source', models.TextField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='drafts.draft')),
            ],
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.UniqueConstraint(fields=('actor', 'run_id', 'problem_id', 'language_id'), name='drafts_actor_run_problem_language_unique'),
        ),
        migrations.AddConstraint(
            model_name='draftrevision',
            constraint=models.UniqueConstraint(fields=('draft', 'revision'), name='drafts_revision_unique'),
        ),
    ]
