"""Trusted host-side Docker launcher for the A3-01 proof harness."""

from __future__ import annotations

import base64
import json
import re
import subprocess
import uuid
from dataclasses import dataclass

IMAGE = "firsterchuv/sandbox-cpp:0.1.0"
MAX_SOURCE_BYTES = 32 * 1024
MAX_ARTIFACT_BYTES = 8 * 1024 * 1024
MAX_INPUT_BYTES = 64 * 1024
MAX_OUTPUT_BYTES = 32 * 1024
MAX_DIAGNOSTICS_BYTES = 8 * 1024
MAX_RESPONSE_BYTES = 12 * 1024 * 1024
OUTER_TIMEOUT_SECONDS = 25
CREATE_TIMEOUT_SECONDS = 15
CLEANUP_TIMEOUT_SECONDS = 10
CONTAINER_PREFIX = "firsterchuv-a3-01-"

RESULT_STATUSES = {
    "COMPILED",
    "EXITED",
    "COMPILE_ERROR",
    "COMPILE_TIMEOUT",
    "COMPILE_ARTIFACT_LIMIT",
    "TIME_LIMIT",
    "OUTPUT_LIMIT",
    "RUNTIME_ERROR",
    "KILLED_UNKNOWN",
    "INFRASTRUCTURE_ERROR",
}


class RunnerInfrastructureError(RuntimeError):
    """Docker could not produce a trustworthy execution result."""


@dataclass(frozen=True)
class ExecutionResult:
    status: str
    exit_code: int | None
    signal: int | None
    stdout: bytes
    stderr: bytes
    artifact: bytes = b""


def encode_request(first: bytes, stdin: bytes, *, first_limit: int = MAX_SOURCE_BYTES) -> bytes:
    if not first or len(first) > first_limit:
        raise ValueError("payload is empty or exceeds the configured limit")
    if len(stdin) > MAX_INPUT_BYTES:
        raise ValueError("stdin exceeds the configured limit")
    return f"{len(first)} {len(stdin)}\n".encode("ascii") + first + stdin


def build_docker_create_args(container_name: str, mode: str) -> list[str]:
    if not re.fullmatch(r"firsterchuv-a3-01-[0-9a-f]{32}", container_name):
        raise ValueError("container name must be generated by this runner")
    if mode not in {"compile", "run"}:
        raise ValueError("container mode must be fixed by the trusted runner")
    return [
        "docker",
        "create",
        "--name",
        container_name,
        "--pull=never",
        "--platform=linux/amd64",
        "--interactive",
        "--attach=stdin",
        "--attach=stdout",
        "--attach=stderr",
        "--network=none",
        "--pid=private",
        "--read-only",
        "--memory=512m",
        "--memory-swap=512m",
        "--cpus=1.0",
        "--pids-limit=64",
        "--user=65534:65534",
        "--cap-drop=ALL",
        "--security-opt=no-new-privileges",
        "--tmpfs",
        "/work:rw,exec,nosuid,nodev,size=64m,uid=65534,gid=65534",
        IMAGE,
        mode,
    ]


def parse_response(data: bytes) -> ExecutionResult:
    if not data or len(data) > MAX_RESPONSE_BYTES:
        raise RunnerInfrastructureError("container response is empty or exceeded its cap")
    try:
        payload = json.loads(data.decode("ascii"))
        if set(payload) != {
            "status", "exitCode", "signal", "stdoutBase64", "stderrBase64", "artifactBase64"
        }:
            raise ValueError("unexpected response fields")
        if payload["status"] not in RESULT_STATUSES:
            raise ValueError("unknown execution status")
        exit_code = payload["exitCode"]
        signal = payload["signal"]
        if exit_code is not None and (not isinstance(exit_code, int) or isinstance(exit_code, bool)):
            raise ValueError("invalid exit code")
        if signal is not None and (not isinstance(signal, int) or isinstance(signal, bool)):
            raise ValueError("invalid signal")
        stdout = base64.b64decode(payload["stdoutBase64"], validate=True)
        stderr = base64.b64decode(payload["stderrBase64"], validate=True)
        artifact = base64.b64decode(payload["artifactBase64"], validate=True)
    except (UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
        raise RunnerInfrastructureError("container returned an invalid protocol response") from error
    if len(stdout) > MAX_OUTPUT_BYTES or len(stderr) > max(MAX_OUTPUT_BYTES, MAX_DIAGNOSTICS_BYTES):
        raise RunnerInfrastructureError("container response exceeded the output limit")
    if len(artifact) > MAX_ARTIFACT_BYTES:
        raise RunnerInfrastructureError("container response exceeded the artifact limit")
    return ExecutionResult(payload["status"], exit_code, signal, stdout, stderr, artifact)


def _run_docker(args: list[str], *, timeout: int, input_data: bytes | None = None) -> subprocess.CompletedProcess[bytes]:
    try:
        return subprocess.run(
            args,
            input=input_data,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
            check=False,
            shell=False,
        )
    except (FileNotFoundError, PermissionError, subprocess.TimeoutExpired, OSError) as error:
        raise RunnerInfrastructureError("Docker CLI or daemon is unavailable") from error


def _cleanup(container_ref: str, *, missing_ok: bool = False) -> None:
    try:
        result = subprocess.run(
            ["docker", "rm", "--force", container_ref],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=CLEANUP_TIMEOUT_SECONDS,
            check=False,
            shell=False,
        )
    except (FileNotFoundError, PermissionError, subprocess.TimeoutExpired, OSError) as error:
        if not missing_ok or not isinstance(error, FileNotFoundError):
            raise RunnerInfrastructureError("failed to remove the runner-owned container") from error
        return
    if result.returncode != 0:
        stderr = result.stderr.lower()
        if missing_ok and (b"no such container" in stderr or b"no such object" in stderr):
            return
        raise RunnerInfrastructureError("failed to remove the runner-owned container")


class DockerRunner:
    def _execute_container(self, mode: str, request: bytes) -> ExecutionResult:
        container_name = CONTAINER_PREFIX + uuid.uuid4().hex
        create_args = build_docker_create_args(container_name, mode)
        try:
            created = _run_docker(create_args, timeout=CREATE_TIMEOUT_SECONDS)
        except RunnerInfrastructureError:
            _cleanup(container_name, missing_ok=True)
            raise
        if created.returncode != 0:
            _cleanup(container_name, missing_ok=True)
            raise RunnerInfrastructureError("Docker could not create the sandbox container")
        try:
            container_id = created.stdout.decode("ascii", errors="strict").strip()
        except UnicodeDecodeError as error:
            _cleanup(container_name, missing_ok=True)
            raise RunnerInfrastructureError("Docker returned a non-ASCII container ID") from error
        if not re.fullmatch(r"[0-9a-f]{64}", container_id):
            _cleanup(container_name, missing_ok=True)
            raise RunnerInfrastructureError("Docker returned an invalid container ID")

        try:
            attached = _run_docker(
                ["docker", "start", "--attach", "--interactive", container_id],
                timeout=OUTER_TIMEOUT_SECONDS,
                input_data=request,
            )
            if attached.returncode != 0 or attached.stderr:
                raise RunnerInfrastructureError("sandbox stopped without a trustworthy result")
            return parse_response(attached.stdout)
        finally:
            _cleanup(container_id)

    def compile(self, source: bytes) -> ExecutionResult:
        request = encode_request(source, b"")
        result = self._execute_container("compile", request)
        if result.status == "COMPILED" and not result.artifact:
            raise RunnerInfrastructureError("compiler returned an empty executable")
        return result

    def run(self, artifact: bytes, stdin: bytes) -> ExecutionResult:
        request = encode_request(artifact, stdin, first_limit=MAX_ARTIFACT_BYTES)
        return self._execute_container("run", request)

    def execute(self, source: bytes, stdin: bytes) -> ExecutionResult:
        compiled = self.compile(source)
        if compiled.status != "COMPILED":
            return compiled
        return self.run(compiled.artifact, stdin)
