# Generated by Django 6.1.2 on 2026-10-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.UUIDField(db_index=True)),
                ('version', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('readiness', models.CharField(choices=[('NOT_READY', 'Не готова'), ('READY', 'Готова')], max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('problem_id', 'version'),
                'constraints': [models.UniqueConstraint(fields=('problem_id', 'version'), name='problems_version_identity_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('problem_id',), name='problems_one_active_version_per_problem')],
            },
        ),
        migrations.CreateModel(
            name='ProblemPublicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('statement_markdown', models.TextField()),
                ('examples', models.JSONField(default=list)),
                ('time_limit_ms', models.PositiveBigIntegerField()),
                ('memory_limit_bytes', models.PositiveBigIntegerField()),
                ('languages', models.JSONField(default=list)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_data', to='problems.problemversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemPrivateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_data', to='problems.problemversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemPrivateArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('checker', 'Checker'), ('validator', 'Validator'), ('reference', 'Reference solution')], max_length=16)),
                ('source_path', models.CharField(max_length=1024)),
                ('language_id', models.CharField(blank=True, max_length=64, null=True)),
                ('contents', models.BinaryField()),
                ('private_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='problems.problemprivatedata')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('private_data', 'role'), name='problems_private_artifact_role_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProblemPublicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=64)),
                ('media_type', models.CharField(max_length=32)),
                ('contents', models.BinaryField()),
                ('public_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='problems.problempublicdata')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('public_data', 'asset_id'), name='problems_public_asset_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('input_data', models.BinaryField()),
                ('expected_output', models.BinaryField(blank=True, null=True)),
                ('private_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='problems.problemprivatedata')),
            ],
            options={
                'ordering': ('ordinal',),
                'constraints': [models.UniqueConstraint(fields=('private_data', 'ordinal'), name='problems_test_ordinal_unique')],
            },
        ),
    ]
