# Generated by Django 6.1.2 on 2026-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.UUIDField()),
                ('match_id', models.UUIDField()),
                ('run_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('score.changed', 'Изменение счёта')], max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['tournament_id', 'id'], name='events_tournament_cursor'), models.Index(fields=['match_id', 'id'], name='events_match_cursor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type', 'score.changed')), name='events_supported_public_type')],
            },
        ),
    ]
