# Generated by Django 6.1.2 on 2026-10-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_matchsnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchevent',
            name='events_supported_public_type',
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('score.changed', 'Изменение счёта'), ('match.admin_action', 'Действие администратора')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='matchevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('score.changed', 'match.admin_action'))), name='events_supported_public_type'),
        ),
    ]
