# Generated by Django 6.1.2 on 2026-10-09 12:23

import backend.apps.tournaments.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('format', models.CharField(choices=[('single_elimination', 'Олимпийская система')], default='single_elimination', max_length=32)),
                ('participant_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('unlisted', 'По ссылке')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирован'), ('running', 'Идёт'), ('completed', 'Завершён'), ('archived', 'Архивирован')], default='draft', max_length=16)),
                ('default_match_config', models.JSONField(default=backend.apps.tournaments.models.default_match_config)),
                ('active_participant_count', models.PositiveIntegerField(default=0, editable=False)),
                ('roster_frozen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_at', 'created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('participant_limit__gte', 2)), name='tournaments_limit_at_least_two'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='tournaments_end_after_start')],
            },
        ),
    ]
