# Generated by Django 6.1.2 on 2026-10-09 12:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('REMOVED', 'Снят')], default='ACTIVE', max_length=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'seed', 'user__display_name', 'user_id'),
                'constraints': [models.UniqueConstraint(fields=('tournament', 'user'), name='unique_tournament_user_entry'), models.UniqueConstraint(condition=models.Q(('seed__isnull', False), ('status', 'ACTIVE')), fields=('tournament', 'seed'), name='unique_active_tournament_seed'), models.CheckConstraint(condition=models.Q(('seed__isnull', True), ('seed__gte', 1), _connector='OR'), name='tournament_seed_positive_or_null')],
            },
        ),
    ]
