# Generated by Django 6.1.2 on 2026-10-09 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueCounter',
            fields=[
                ('scope_key', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('pending_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_id', models.UUIDField(db_index=True)),
                ('run_id', models.UUIDField(db_index=True)),
                ('problem_id', models.UUIDField(db_index=True)),
                ('language_id', models.CharField(max_length=64)),
                ('source', models.TextField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('request_sha256', models.CharField(max_length=64)),
                ('idempotency_sha256', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField()),
                ('elapsed_ms', models.PositiveBigIntegerField()),
                ('scoring_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'В очереди'), ('RUNNING', 'Проверяется'), ('RETRY_WAIT', 'Повтор проверки'), ('FINISHED', 'Проверена'), ('INFRA_FAILED', 'Ошибка инфраструктуры'), ('CANCELLED', 'Отменена')], default='QUEUED', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('OK', 'OK'), ('WA', 'WA'), ('TL', 'TL'), ('ML', 'ML'), ('RE', 'RE'), ('CE', 'CE')], max_length=8, null=True)),
                ('compile_diagnostics', models.TextField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('internal_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает публикации'), ('SENDING', 'Публикуется'), ('SENT', 'Опубликована')], default='PENDING', max_length=8)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result_outbox', to='submissions.submission')),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'available_at', 'received_at'], name='submissions_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'lease_until'], name='submissions_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('actor', 'idempotency_sha256'), name='submissions_actor_idempotency_unique'),
        ),
    ]
