"""Trusted host-side Docker launcher shared by LocalJudge and sandbox smoke."""

from __future__ import annotations

import base64
import json
import os
import re
import selectors
import subprocess
import time
import uuid
from dataclasses import dataclass
from datetime import datetime
from uuid import UUID

IMAGE = "firsterchuv/sandbox-cpp:0.1.0"
MAX_SOURCE_BYTES = 32 * 1024
MAX_ARTIFACT_BYTES = 8 * 1024 * 1024
MAX_INPUT_BYTES = 8 * 1024 * 1024
MAX_OUTPUT_BYTES = 32 * 1024
MAX_DIAGNOSTICS_BYTES = 8 * 1024
MIN_MEMORY_LIMIT_BYTES = 32 * 1024 * 1024
MAX_MEMORY_LIMIT_BYTES = 512 * 1024 * 1024
MAX_RUN_TIME_LIMIT_MS = 120_000
DEFAULT_RUN_TIME_LIMIT_MS = 2_000
MAX_RESPONSE_BYTES = 12 * 1024 * 1024
MAX_DOCKER_STDERR_BYTES = 64 * 1024
DOCKER_READ_CHUNK_BYTES = 64 * 1024
OUTER_TIMEOUT_SECONDS = 25
CREATE_TIMEOUT_SECONDS = 15
CLEANUP_TIMEOUT_SECONDS = 10
CONTAINER_PREFIX = "firsterchuv-a3-01-"
OWNER_LABEL = "io.firsterchuv.owner"
SUBMISSION_LABEL = "io.firsterchuv.submission"
LEASE_LABEL = "io.firsterchuv.lease"
OWNER_VALUE = "submission-worker"


@dataclass(frozen=True, slots=True)
class SandboxClaim:
    submission_id: UUID
    lease_token: UUID

RESULT_STATUSES = {
    "COMPILED",
    "EXITED",
    "COMPILE_ERROR",
    "COMPILE_TIMEOUT",
    "COMPILE_ARTIFACT_LIMIT",
    "TIME_LIMIT",
    "OUTPUT_LIMIT",
    "RUNTIME_ERROR",
    "KILLED_UNKNOWN",
    "INFRASTRUCTURE_ERROR",
}
CPP20_COMPILER_ARGV = (
    "g++",
    "-std=c++20",
    "-O2",
    "-pipe",
    "-fno-diagnostics-color",
    "-fmax-errors=20",
    "/work/main.cpp",
    "-o",
    "/work/program",
)


class RunnerInfrastructureError(RuntimeError):
    """Docker could not produce a trustworthy execution result."""


@dataclass(frozen=True)
class ExecutionResult:
    status: str
    exit_code: int | None
    signal: int | None
    stdout: bytes
    stderr: bytes
    artifact: bytes = b""
    elapsed_ms: int = 0


def encode_request(first: bytes, stdin: bytes, *, first_limit: int = MAX_SOURCE_BYTES) -> bytes:
    if not first or len(first) > first_limit:
        raise ValueError("payload is empty or exceeds the configured limit")
    if len(stdin) > MAX_INPUT_BYTES:
        raise ValueError("stdin exceeds the configured limit")
    return f"{len(first)} {len(stdin)}\n".encode("ascii") + first + stdin


def build_docker_create_args(
    container_name: str,
    mode: str,
    *,
    memory_limit_bytes: int = MAX_MEMORY_LIMIT_BYTES,
    time_limit_ms: int = DEFAULT_RUN_TIME_LIMIT_MS,
    claim: SandboxClaim | None = None,
) -> list[str]:
    if not re.fullmatch(r"firsterchuv-a3-01-[0-9a-f]{32}", container_name):
        raise ValueError("container name must be generated by this runner")
    if mode not in {"compile", "run"}:
        raise ValueError("container mode must be fixed by the trusted runner")
    if (
        not isinstance(memory_limit_bytes, int)
        or isinstance(memory_limit_bytes, bool)
        or not MIN_MEMORY_LIMIT_BYTES <= memory_limit_bytes <= MAX_MEMORY_LIMIT_BYTES
    ):
        raise ValueError("memory limit is outside the sandbox policy")
    if (
        not isinstance(time_limit_ms, int)
        or isinstance(time_limit_ms, bool)
        or not 1 <= time_limit_ms <= MAX_RUN_TIME_LIMIT_MS
    ):
        raise ValueError("time limit is outside the sandbox policy")
    command = [
        "docker",
        "create",
        "--name",
        container_name,
        "--pull=never",
        "--platform=linux/amd64",
        "--interactive",
        "--attach=stdin",
        "--attach=stdout",
        "--attach=stderr",
        "--network=none",
        "--read-only",
        f"--memory={memory_limit_bytes}",
        f"--memory-swap={memory_limit_bytes}",
        "--cpus=1.0",
        "--pids-limit=64",
        "--user=65534:65534",
        "--cap-drop=ALL",
        "--security-opt=no-new-privileges",
        "--tmpfs",
        "/work:rw,exec,nosuid,nodev,size=64m,uid=65534,gid=65534",
        IMAGE,
        mode,
    ]
    if claim is not None:
        if (
            not isinstance(claim, SandboxClaim)
            or not isinstance(claim.submission_id, UUID)
            or not isinstance(claim.lease_token, UUID)
        ):
            raise ValueError("sandbox claim metadata must be trusted worker data")
        command[command.index("--pull=never"):command.index("--pull=never")] = [
            "--label", f"{OWNER_LABEL}={OWNER_VALUE}",
            "--label", f"{SUBMISSION_LABEL}={claim.submission_id}",
            "--label", f"{LEASE_LABEL}={claim.lease_token}",
        ]
    if mode == "run":
        command.append(str(time_limit_ms))
    return command


def parse_response(data: bytes) -> ExecutionResult:
    if not data or len(data) > MAX_RESPONSE_BYTES:
        raise RunnerInfrastructureError("container response is empty or exceeded its cap")
    try:
        payload = json.loads(data.decode("ascii"))
        if set(payload) != {
            "status", "exitCode", "signal", "stdoutBase64", "stderrBase64", "artifactBase64"
        }:
            raise ValueError("unexpected response fields")
        if payload["status"] not in RESULT_STATUSES:
            raise ValueError("unknown execution status")
        exit_code = payload["exitCode"]
        signal = payload["signal"]
        if exit_code is not None and (not isinstance(exit_code, int) or isinstance(exit_code, bool)):
            raise ValueError("invalid exit code")
        if signal is not None and (not isinstance(signal, int) or isinstance(signal, bool)):
            raise ValueError("invalid signal")
        stdout = base64.b64decode(payload["stdoutBase64"], validate=True)
        stderr = base64.b64decode(payload["stderrBase64"], validate=True)
        artifact = base64.b64decode(payload["artifactBase64"], validate=True)
    except (UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
        raise RunnerInfrastructureError("container returned an invalid protocol response") from error
    if len(stdout) > MAX_OUTPUT_BYTES or len(stderr) > max(MAX_OUTPUT_BYTES, MAX_DIAGNOSTICS_BYTES):
        raise RunnerInfrastructureError("container response exceeded the output limit")
    if len(artifact) > MAX_ARTIFACT_BYTES:
        raise RunnerInfrastructureError("container response exceeded the artifact limit")
    return ExecutionResult(payload["status"], exit_code, signal, stdout, stderr, artifact)


def _run_docker(
    args: list[str],
    *,
    timeout: int,
    input_data: bytes | None = None,
    stdout_limit: int = MAX_RESPONSE_BYTES,
    stderr_limit: int = MAX_DOCKER_STDERR_BYTES,
) -> subprocess.CompletedProcess[bytes]:
    process: subprocess.Popen[bytes] | None = None
    selector = selectors.DefaultSelector()
    stdout = bytearray()
    stderr = bytearray()
    input_offset = 0
    stdin_pipe = None
    try:
        process = subprocess.Popen(
            args,
            stdin=subprocess.PIPE if input_data else subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=False,
        )
        assert process.stdout is not None and process.stderr is not None
        os.set_blocking(process.stdout.fileno(), False)
        os.set_blocking(process.stderr.fileno(), False)
        selector.register(process.stdout, selectors.EVENT_READ, ("stdout", stdout, stdout_limit))
        selector.register(process.stderr, selectors.EVENT_READ, ("stderr", stderr, stderr_limit))
        if input_data:
            stdin_pipe = process.stdin
            assert stdin_pipe is not None
            os.set_blocking(stdin_pipe.fileno(), False)
            selector.register(stdin_pipe, selectors.EVENT_WRITE, input_data)

        deadline = time.monotonic() + timeout
        while selector.get_map():
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise RunnerInfrastructureError("Docker CLI or daemon timed out")
            for key, _ in selector.select(min(remaining, 0.1)):
                if isinstance(key.data, tuple) and key.data[0] in {"stdout", "stderr"}:
                    stream_name, target, limit = key.data
                    try:
                        chunk = os.read(key.fileobj.fileno(), min(DOCKER_READ_CHUNK_BYTES, limit - len(target) + 1))
                    except BlockingIOError:
                        continue
                    if not chunk:
                        selector.unregister(key.fileobj)
                        key.fileobj.close()
                        continue
                    if len(target) + len(chunk) > limit:
                        raise RunnerInfrastructureError(f"Docker {stream_name} exceeded its output cap")
                    target.extend(chunk)
                    continue

                if input_data is not None and input_offset < len(input_data):
                    try:
                        written = os.write(
                            key.fileobj.fileno(),
                            input_data[input_offset:input_offset + DOCKER_READ_CHUNK_BYTES],
                        )
                    except (BrokenPipeError, ConnectionResetError):
                        written = 0
                        input_offset = len(input_data)
                    except BlockingIOError:
                        continue
                    input_offset += written
                if input_data is None or input_offset >= len(input_data):
                    selector.unregister(key.fileobj)
                    key.fileobj.close()
                    stdin_pipe = None

        returncode = process.wait(timeout=max(0.001, deadline - time.monotonic()))
        return subprocess.CompletedProcess(args, returncode, bytes(stdout), bytes(stderr))
    except RunnerInfrastructureError:
        raise
    except (FileNotFoundError, PermissionError, subprocess.TimeoutExpired, OSError) as error:
        raise RunnerInfrastructureError("Docker CLI or daemon is unavailable") from error
    finally:
        selector.close()
        if process is not None:
            for pipe in (stdin_pipe, process.stdout, process.stderr):
                if pipe is not None and not pipe.closed:
                    pipe.close()
            if process.poll() is None:
                process.kill()
                process.wait()


def _cleanup(container_ref: str, *, missing_ok: bool = False) -> None:
    try:
        result = _run_docker(
            ["docker", "rm", "--force", container_ref],
            timeout=CLEANUP_TIMEOUT_SECONDS,
        )
    except RunnerInfrastructureError as error:
        if not missing_ok or not isinstance(error.__cause__, FileNotFoundError):
            raise RunnerInfrastructureError("failed to remove the runner-owned container") from error
        return
    if result.returncode != 0:
        stderr = result.stderr.lower()
        if missing_ok and (b"no such container" in stderr or b"no such object" in stderr):
            return
        raise RunnerInfrastructureError("failed to remove the runner-owned container")


def cleanup_orphaned_claim_containers(*, now: datetime | None = None) -> int:
    """Remove only this worker's containers whose exact DB lease is no longer live."""
    from django.utils import timezone

    from backend.apps.submissions.models import Submission

    current_time = now or timezone.now()
    if not timezone.is_aware(current_time):
        raise ValueError("container recovery time must be timezone-aware")
    listed = _run_docker(
        [
            "docker", "ps", "--all", "--quiet", "--no-trunc",
            "--filter", f"label={OWNER_LABEL}={OWNER_VALUE}",
        ],
        timeout=CREATE_TIMEOUT_SECONDS,
        stdout_limit=64 * 1024,
    )
    if listed.returncode != 0 or listed.stderr:
        raise RunnerInfrastructureError("Docker could not list worker-owned sandbox containers")

    removed = 0
    for raw_id in listed.stdout.splitlines():
        container_id = raw_id.decode("ascii", errors="ignore").strip()
        if not re.fullmatch(r"[0-9a-f]{64}", container_id):
            raise RunnerInfrastructureError("Docker returned an invalid sandbox container ID")
        inspected = _run_docker(
            ["docker", "inspect", f"--format={{json .Config.Labels}}", container_id],
            timeout=CREATE_TIMEOUT_SECONDS,
            stdout_limit=4096,
        )
        if inspected.returncode != 0 or inspected.stderr:
            raise RunnerInfrastructureError("Docker could not confirm sandbox ownership")
        try:
            labels = json.loads(inspected.stdout.decode("ascii"))
            submission_id = UUID(labels[SUBMISSION_LABEL])
            lease_token = UUID(labels[LEASE_LABEL])
        except (UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
            # A malformed/foreign container is never eligible for removal.
            raise RunnerInfrastructureError("worker sandbox is missing valid claim labels") from error
        if labels.get(OWNER_LABEL) != OWNER_VALUE:
            raise RunnerInfrastructureError("Docker returned a container outside worker ownership")
        if Submission.objects.filter(
            pk=submission_id,
            status=Submission.Status.RUNNING,
            lease_token=lease_token,
            lease_until__gt=current_time,
        ).exists():
            continue
        _cleanup(container_id)
        removed += 1
    return removed


class DockerRunner:
    def __init__(self, *, claim: SandboxClaim | None = None) -> None:
        self._claim = claim

    def supports_compiler(self, compiler: object) -> bool:
        return bool(
            getattr(compiler, "language_id", None) == "cpp20"
            and getattr(compiler, "image", None) == IMAGE
            and getattr(compiler, "source_filename", None) == "main.cpp"
            and getattr(compiler, "compile_argv", None) == CPP20_COMPILER_ARGV
        )

    @staticmethod
    def _inspect_oom(container_id: str) -> bool:
        if not re.fullmatch(r"[0-9a-f]{64}", container_id):
            raise RunnerInfrastructureError("container ID is not owned by this runner")
        result = _run_docker(
            ["docker", "inspect", "--format={{.State.OOMKilled}}", container_id],
            timeout=CREATE_TIMEOUT_SECONDS,
            stdout_limit=32,
            stderr_limit=MAX_DOCKER_STDERR_BYTES,
        )
        if result.returncode != 0 or result.stderr:
            raise RunnerInfrastructureError("Docker could not confirm sandbox OOM state")
        state = result.stdout.strip()
        if state == b"true":
            return True
        if state == b"false":
            return False
        raise RunnerInfrastructureError("Docker returned an invalid sandbox OOM state")

    def _execute_container(
        self,
        mode: str,
        request: bytes,
        *,
        memory_limit_bytes: int = MAX_MEMORY_LIMIT_BYTES,
        time_limit_ms: int = DEFAULT_RUN_TIME_LIMIT_MS,
    ) -> ExecutionResult:
        container_name = CONTAINER_PREFIX + uuid.uuid4().hex
        create_args = build_docker_create_args(
            container_name,
            mode,
            memory_limit_bytes=memory_limit_bytes,
            time_limit_ms=time_limit_ms,
            claim=self._claim,
        )
        try:
            created = _run_docker(create_args, timeout=CREATE_TIMEOUT_SECONDS)
        except RunnerInfrastructureError:
            _cleanup(container_name, missing_ok=True)
            raise
        if created.returncode != 0:
            _cleanup(container_name, missing_ok=True)
            raise RunnerInfrastructureError("Docker could not create the sandbox container")
        try:
            container_id = created.stdout.decode("ascii", errors="strict").strip()
        except UnicodeDecodeError as error:
            _cleanup(container_name, missing_ok=True)
            raise RunnerInfrastructureError("Docker returned a non-ASCII container ID") from error
        if not re.fullmatch(r"[0-9a-f]{64}", container_id):
            _cleanup(container_name, missing_ok=True)
            raise RunnerInfrastructureError("Docker returned an invalid container ID")

        try:
            started = time.monotonic()
            attached = _run_docker(
                ["docker", "start", "--attach", "--interactive", container_id],
                timeout=(
                    OUTER_TIMEOUT_SECONDS
                    if mode == "compile"
                    else max(5, time_limit_ms / 1000 + 5)
                ),
                input_data=request,
            )
            if attached.returncode != 0 or attached.stderr:
                if self._inspect_oom(container_id):
                    return ExecutionResult(
                        "MEMORY_LIMIT",
                        None,
                        None,
                        b"",
                        b"",
                        elapsed_ms=int((time.monotonic() - started) * 1000),
                    )
                raise RunnerInfrastructureError("sandbox stopped without a trustworthy result")
            result = parse_response(attached.stdout)
            if result.status == "KILLED_UNKNOWN" and self._inspect_oom(container_id):
                return ExecutionResult(
                    "MEMORY_LIMIT",
                    None,
                    result.signal,
                    result.stdout,
                    result.stderr,
                    elapsed_ms=int((time.monotonic() - started) * 1000),
                )
            return ExecutionResult(
                result.status,
                result.exit_code,
                result.signal,
                result.stdout,
                result.stderr,
                result.artifact,
                elapsed_ms=int((time.monotonic() - started) * 1000),
            )
        finally:
            _cleanup(container_id)

    def compile(self, source: bytes) -> ExecutionResult:
        request = encode_request(source, b"")
        result = self._execute_container("compile", request)
        if result.status == "COMPILED" and not result.artifact:
            raise RunnerInfrastructureError("compiler returned an empty executable")
        return result

    def run(
        self,
        artifact: bytes,
        stdin: bytes,
        *,
        time_limit_ms: int = DEFAULT_RUN_TIME_LIMIT_MS,
        memory_limit_bytes: int = MAX_MEMORY_LIMIT_BYTES,
    ) -> ExecutionResult:
        request = encode_request(artifact, stdin, first_limit=MAX_ARTIFACT_BYTES)
        return self._execute_container(
            "run",
            request,
            memory_limit_bytes=memory_limit_bytes,
            time_limit_ms=time_limit_ms,
        )

    def execute(
        self,
        source: bytes,
        stdin: bytes,
        *,
        time_limit_ms: int = DEFAULT_RUN_TIME_LIMIT_MS,
        memory_limit_bytes: int = MAX_MEMORY_LIMIT_BYTES,
    ) -> ExecutionResult:
        compiled = self.compile(source)
        if compiled.status != "COMPILED":
            return compiled
        return self.run(
            compiled.artifact,
            stdin,
            time_limit_ms=time_limit_ms,
            memory_limit_bytes=memory_limit_bytes,
        )
