# Generated by Django 6.1.2 on 2026-10-09 13:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0002_tournamentparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bracket_key', models.CharField(max_length=32)),
                ('round_index', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('MATCH', 'Матч'), ('BYE', 'Автоматический проход')], max_length=8)),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает'), ('READY', 'Готов'), ('RUNNING', 'Идёт'), ('PAUSED', 'Пауза'), ('FINALIZING', 'Проверяются посылки'), ('FINISHED', 'Завершён'), ('TIED', 'Ничья'), ('BYE', 'Автоматический проход')], default='WAITING', max_length=12)),
                ('next_slot', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_matches', to='competition.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_matches_won', to='tournaments.tournamentparticipant')),
            ],
            options={
                'ordering': ('round_index', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает'), ('READY', 'Готов'), ('RUNNING', 'Идёт'), ('PAUSED', 'Пауза'), ('FINALIZING', 'Проверяются посылки'), ('FINISHED', 'Завершён'), ('TIED', 'Ничья'), ('SUPERSEDED', 'Заменён повторным матчем')], default='WAITING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_pause_ms', models.PositiveBigIntegerField(default=0)),
                ('allowed_duration_ms', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('score_rule', models.JSONField(default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('technical_reason', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='competition.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_runs_won', to='tournaments.tournamentparticipant')),
            ],
            options={
                'ordering': ('match_id', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='current_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_match', to='competition.matchrun'),
        ),
        migrations.CreateModel(
            name='MatchSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('resolution', models.CharField(choices=[('PLAYER', 'Участник'), ('BYE', 'Пустой слот'), ('WAITING', 'Ожидает предыдущий матч')], max_length=8)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='competition.match')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_match_slots', to='tournaments.tournamentparticipant')),
                ('upstream_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downstream_slots', to='competition.match')),
            ],
            options={
                'ordering': ('match_id', 'slot_index'),
            },
        ),
        migrations.AddConstraint(
            model_name='matchrun',
            constraint=models.UniqueConstraint(fields=('match', 'sequence'), name='unique_match_run_sequence'),
        ),
        migrations.AddConstraint(
            model_name='matchrun',
            constraint=models.CheckConstraint(condition=models.Q(('allowed_duration_ms__gte', 1)), name='match_run_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'round_index', 'position'), name='unique_tournament_round_position'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'bracket_key'), name='unique_tournament_bracket_key'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('next_match__isnull', False)), fields=('next_match', 'next_slot'), name='unique_match_advancement_target'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('next_match__isnull', True), ('next_slot__isnull', True)), models.Q(('next_match__isnull', False), ('next_slot__in', (0, 1)), models.Q(('next_match', models.F('id')), _negated=True)), _connector='OR'), name='match_advancement_target_complete'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'BYE'), ('status', 'BYE'), ('winner__isnull', False)), models.Q(('kind', 'MATCH'), ('status__in', ('WAITING', 'READY', 'RUNNING', 'PAUSED', 'FINALIZING', 'FINISHED', 'TIED'))), _connector='OR'), name='match_bye_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='matchslot',
            constraint=models.UniqueConstraint(fields=('match', 'slot_index'), name='unique_match_slot_index'),
        ),
        migrations.AddConstraint(
            model_name='matchslot',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('match', 'participant'), name='unique_participant_per_match'),
        ),
        migrations.AddConstraint(
            model_name='matchslot',
            constraint=models.CheckConstraint(condition=models.Q(('slot_index__in', (0, 1))), name='match_slot_index_valid'),
        ),
        migrations.AddConstraint(
            model_name='matchslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', 'PLAYER'), ('participant__isnull', False)), models.Q(('resolution', 'BYE'), ('participant__isnull', True), ('upstream_match__isnull', True)), models.Q(('resolution', 'WAITING'), ('participant__isnull', True), ('upstream_match__isnull', False)), _connector='OR'), name='match_slot_resolution_consistent'),
        ),
        migrations.AddConstraint(
            model_name='matchslot',
            constraint=models.CheckConstraint(condition=models.Q(('upstream_match__isnull', True), models.Q(('upstream_match', models.F('match')), _negated=True), _connector='OR'), name='match_slot_not_own_upstream'),
        ),
    ]
