# Generated by Django 6.1.2 on 2026-10-09 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('tournaments', '0003_invite_inviteacceptance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketCommandReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('bracket.pairings', 'Ручные пары'), ('bracket.reset', 'Сброс сетки')], max_length=32)),
                ('idempotency_sha256', models.CharField(max_length=64)),
                ('request_sha256', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bracket_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_command_receipts', to='tournaments.tournament')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tournament', 'idempotency_sha256'), name='unique_tournament_bracket_command_key')],
            },
        ),
    ]
