# Generated by Django 6.1.2 on 2026-10-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_bracketcommandreceipt'),
        ('tournaments', '0003_invite_inviteacceptance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrun',
            name='problem_versions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='start_mode',
            field=models.CharField(choices=[('manual', 'Ручной запуск'), ('both_ready', 'После готовности обоих')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='MatchRunReady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_run_ready_signals', to='tournaments.tournamentparticipant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_signals', to='competition.matchrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'participant'), name='unique_match_run_ready_participant')],
            },
        ),
    ]
