# Generated by Django 6.1.2 on 2026-10-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_matchrun_problem_versions_matchrun_start_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAttempt',
            fields=[
                ('submission_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('problem_id', models.UUIDField()),
                ('received_at', models.DateTimeField()),
                ('elapsed_ms', models.PositiveBigIntegerField()),
                ('scoring_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('received_at', 'submission_id'),
            },
        ),
        migrations.AddField(
            model_name='matchrun',
            name='score_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='scoring_version',
            field=models.CharField(default='scoring-v1', max_length=64),
        ),
        migrations.CreateModel(
            name='AttemptResult',
            fields=[
                ('accepted', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='result', serialize=False, to='competition.acceptedattempt')),
                ('verdict', models.CharField(choices=[('OK', 'Accepted'), ('WA', 'Wrong answer'), ('TL', 'Time limit'), ('ML', 'Memory limit'), ('RE', 'Runtime error'), ('CE', 'Compile error')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='acceptedattempt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_attempts', to='competition.matchrun'),
        ),
        migrations.AddConstraint(
            model_name='acceptedattempt',
            constraint=models.CheckConstraint(condition=models.Q(('elapsed_ms__gte', 0)), name='accepted_attempt_elapsed_nonnegative'),
        ),
    ]
