# Generated by Django 6.1.2 on 2026-10-09 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_acceptedattempt_matchrun_score_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAdminCommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=32)),
                ('request_sha256', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_admin_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_command_receipts', to='competition.match')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_command_receipts', to='competition.matchrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'command_id'), name='unique_match_admin_command_id')],
            },
        ),
    ]
