# Generated by Django 6.1.2 on 2026-10-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_matchadmincommandreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrun',
            name='participant_user_ids',
            field=models.JSONField(default=list),
        ),
    ]
