# Generated by Django 6.1.2 on 2026-10-10 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_matchrun_participant_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureFailureRecord',
            fields=[
                ('accepted', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='infrastructure_failure', serialize=False, to='competition.acceptedattempt')),
                ('reason_code', models.CharField(max_length=64)),
                ('retryable', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
